[project]
name = "ds-ecommerce-olist"
version = "0.1.0"
description = "End-to-end Data Science project based on e-commerce data from Brazil (by Olist)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
